version: '3.8'

services:
  app:
    image: ${ECR_REGISTRY}/${ECR_REPOSITORY}:${IMAGE_TAG}
    container_name: dev-inbuildify-app
    restart: unless-stopped
    ports:
      - "5000:5000"
    env_file:
      - .env
    networks:
      - app-network

  worker:
    image: ${ECR_REGISTRY}/${ECR_REPOSITORY}:${IMAGE_TAG}
    container_name: dev-inbuildify-worker
    restart: unless-stopped
    command: npm run start:worker
    env_file:
      - .env
    networks:
      - app-network

  socket:
    image: ${ECR_REGISTRY}/${ECR_REPOSITORY}:${IMAGE_TAG}
    container_name: dev-inbuildify-socket
    restart: unless-stopped
    command: npm run start:socket
    env_file:
      - .env
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
